### ISSUE TITLE
Implement deadline calculation on proxy

### ISSUE THREAD

**Issue by ManasVegi** [dqian3/DOM-BFT#13]
Currently, the proxy just takes the last One Way Delay measurements from each receiver and uses those to calculate the deadline. We would want to keep some window of OWD messages and calculate the 90th percentile as specified in the protocol.

**Comment by Steamgjk** [comment]
If deployed in WAN, 50th percentile should already be sufficient and stable.
Make the percentile as a configurable parameter and later we may need to do ablation study.
